FROM node:18

WORKDIR /app

RUN npm install --force -g yarn

COPY package.json ./
COPY yarn.lock ./

RUN yarn

COPY . .

ENV COOKIE_PW=${COOKIE_PW}
ENV MYSQL_HOST=${MYSQL_HOST}
ENV MYSQL_PW=${MYSQL_PW}
ENV MYSQL_PORT=${MYSQL_PORT}
ENV MYSQL_DB=${MYSQL_DB}
ENV MYSQL_USER=${MYSQL_USER}
ENV ALLOWED_ID=${ALLOWED_ID}

RUN yarn build

EXPOSE 3000

CMD ["yarn", "start"]